version: '3'

services:
  app:
    build: .
    container_name: admin-video-typescript
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
  
  db:
    image: mysql:8.0.30-debian
    container_name: admin-video-typescript-db
    profiles:
      - dev
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    ports:
      - 3307:3306

  db_teste:
    image: mysql:8.0.30-debian
    container_name: admin-video-typescript-db
    environment:
      - MYSQL_DATABASE=micro_videos_test
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql